### ISSUE TITLE
Translation failed due to token-limit exceeded

### ISSUE THREAD

**Issue by makeitr3al** [3ru/gpt-translate#28]
Hi @3ru 
I recently updated to GPT 4 and since then, I'm facing more often the following issue. And I've changed only a few words on one page (so basically just one file had changed...). This didn't happened with GPT 3.5
I thought GPT 4 has a higher limit?

429 error ref: https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests

![image](https://github.com/3ru/gpt-translate/assets/132067780/5a992abe-deff-4b90-b627-7da41e745d65)

**Comment by makeitr3al** [comment]
@3ru It's occasional and usually a re-run had solved an issue like that. But it seems as there are some rules that doesn't allow any translation because the job terminates after just 3 seconds without even trying to translate.

**Comment by makeitr3al** [comment]
@3ru 
Maybe I try to translate into too much languages? Could we split the calls?

**Comment by makeitr3al** [comment]
@3ru 
Sorry for another ping. Just saw, that there is also an error message that give a hint that there may no rights to access the model GPT 4. I hope I don't need to switch the API key, should work anyway, shouldn't it?

**Comment by makeitr3al** [comment]
@3ru 
Yes just saw that too. From my point it's absolutely secondary if it takes longer to execute the translation. I'd prefer to have a more accurate translation than have it done in under a minute.

Maybe that helps: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_handle_rate_limits.ipynb

**Comment by 3ru** [comment]
@makeitr3al 
As an interim solution, I have made a release with a translation delay.
My ideal would be to have a fast and accurate translation, but I don't have the time to envision it at this time.

I would like you to try this delay for a while to see if it works properly. If there are any problems, please re-open this issue.

**Comment by 3ru** [comment]
I'll see if I can increase the delay or find another way.

**Comment by makeitr3al** [comment]
Hi @3ru 
Any news on this one?
Cheers

**Comment by 3ru** [comment]
@makeitr3al 

I have been doing some testing in my environment and it is impractical for me to translate multiple languages and files for you due to the limitations of gpt-4.
GPT-4 currently has a strong limit of 10,000 tokens and 5 requests per minute. However, even with a proper 1-minute delay, errors can still occur and I am not sure how long to wait.

![image](https://github.com/3ru/gpt-translate/assets/69892552/fd2e12f2-7f8a-449e-bb0b-869fb3e8f569)


I personally recommend gpt-3.5 for financial, time, and language freedom.

As you can see financially, requests to gpt-4 are expensive. 
Also, if we sandwich in a generous delay to get around the strong limit, it takes about 5 minutes per file. With multiple languages, this is n times longer.
Finally, linguistic freedom is lost. Since gpt-4 is trained to be used more safely, translations are skipped if there are words that are considered inappropriate.

**Comment by 3ru** [comment]
Feel free to reopen if you have any problems.
